┌─╴CommandDef
  ~ {Args Options}

  ┌─╴ArgDef
    |Single
    |Rest
  └─╴

  ┌─╴OptionDef
    ~ {Type Names}

    ┌─╴Type
      |Boolean
      |Occurrences
      |Value
      |Values
    └─╴
  └─╴

└─╴

┌─╴Command
  ~ {Args Options}

  ┌─╴Arg
    |Single {Present Value}
    |Rest {Values}
  └─╴

  ┌─╴Option
    |Boolean {Present}
    |Occurrences {Occurrences}
    |Value {Present Value}
    |Values {Values}
  └─╴
└─╴
